import asyncio
import urllib.parse
from argparse import ArgumentParser
from typing import Optional, List, Dict

import httpx
import instructor
import yaml
from json_schema_to_pydantic import create_model
from pydantic import BaseModel, Field, HttpUrl
from rich.console import Console

from kavalai.tools.openapi_spec_parser import OpenApiSpecParser


class TaskConfig(BaseModel):
    # The server URL of the agent. Must have POST /run_agent available.
    agent_server_url: HttpUrl

    # Agent basic auth credentials.
    auth_username: str
    auth_password: str

    # Task descriptions with number of turns the persona is supposed to talk with it.
    llm_provider: Optional[str] = None
    task: str
    max_turns: int = Field(gt=0, description="The maximum number of conversation turns")


class PersonaConfig(BaseModel):
    """Schema for the configuration YAML file."""

    name: str
    persona_description: str
    mood: str


console = Console()


async def run_simulation(task_yaml_path: str, persona_yaml_path: str):
    # Load task and persona configurations.
    with open(task_yaml_path) as f:
        task_config = TaskConfig(**yaml.safe_load(f))
    with open(persona_yaml_path) as f:
        persona_config = PersonaConfig(**yaml.safe_load(f))

    # Setup the LLM client and chat history.
    llm_client = instructor.from_provider(
        task_config.llm_provider, async_client=True, mode=instructor.Mode.JSON
    )
    history: List[Dict[str, str]] = []

    # We'll keep track of the session_id given by the agent.
    agent_session_id: Optional[str] = None

    auth = (
        (task_config.auth_username, task_config.auth_password)
        if task_config.auth_username
        else None
    )

    async with httpx.AsyncClient(auth=auth, timeout=60.0) as client:
        console.print(
            f"[bold green] Starting simulation with {persona_config.name}...[/bold green]\n"
        )

        # Load agent input and output schemas from the agent server's OpenAPI specification.
        openapi_spec_url = urllib.parse.urljoin(
            str(task_config.agent_server_url), "/openapi.json"
        )
        console.print(f"Loading OpenAPI specification from {openapi_spec_url}")
        spec = await client.get(openapi_spec_url)
        spec.raise_for_status()
        parser = OpenApiSpecParser(spec.json())

        input_schema = (
            create_model(parser.get_path_request_schema("/run_agent", "POST"))
            .model_fields["data"]
            .annotation
        )
        output_schema = (
            create_model(parser.get_path_response_schema("/run_agent", "POST"))
            .model_fields["data"]
            .annotation
        )

        console.print(
            f"[bold white]Input schema: {input_schema.model_fields}[/bold white]"
        )
        console.print(
            f"[bold white]Output schema: {output_schema.model_fields}[/bold white]"
        )

        # We'll ask the LLM to fill in the persona's thought process and agent input data produced by the invocation.
        class PersonaResponse(BaseModel):
            thought: str
            terminate: bool = False
            data: input_schema

        for turn_idx in range(task_config.max_turns):
            system_message = f"""Task: You are a persona pretending to be an user.
            In the message history, "user" messages are actually generated by you.
            "assistant" messages are from an agent we are testing.

            Steps:
            1. Analyze the message history, don't ask questions you have already answers to.
            2. Don't say things you have already said.
            3. If the agent can't help you, try to help them. Ask questions how you can present your task more clearly.
            4. If you have everything you need, terminate the conservation.

            Output instructions:
            1. Don't overshare details unless they are required.
            2. Keep the conversation flowing.

            User task: {task_config.task}
            Persona: {persona_config.model_dump()}
            """
            all_messages = [{"role": "system", "content": system_message}] + history

            # console.print(f"Message history: {history}")

            resp = await llm_client.chat.completions.create(
                response_model=PersonaResponse, messages=all_messages
            )

            console.print(f"[bold white][Turn {turn_idx + 1}][/bold white]")
            console.print(
                f"[white][Turn {turn_idx + 1}](thinking) {resp.thought}[/white]"
            )
            if resp.terminate:
                console.print(
                    "[yellow] Persona decided to end the conversation.[/yellow]"
                )
                break

            console.print(
                f"[bold blue]{persona_config.name}:[/bold blue] [blue]{resp.data.user_message}[/blue]"
            )
            history.append({"role": "user", "content": resp.data.user_message})

            # 3. REST API Call to Kaval.AI Server
            # The payload matches the 'InputType' defined in server.py
            payload = {
                "session_id": agent_session_id,
                "external_id": f"Persona: {persona_config.name}",
                "data": resp.data.model_dump(),
            }

            url = f"{str(task_config.agent_server_url).rstrip('/')}/run_agent"

            try:
                # Post the payload to the agent.
                r = await client.post(url, json=payload)
                r.raise_for_status()

                response_json = r.json()
                agent_session_id = response_json.get("session_id")
                agent_response = response_json["data"]["agent_response"]
                console.print(
                    f"[bold yellow][Turn {turn_idx + 1}] Agent:[/bold yellow] [yellow]{agent_response}[/yellow]\n"
                )
                history.append({"role": "assistant", "content": agent_response})

            except httpx.HTTPStatusError:
                console.print(
                    f"[bold red] Server Error ({r.status_code}):[/bold red] {r.text}"
                )
                break
            except Exception as e:
                console.print(f"[bold red] Connection Error:[/bold red] {e}")
                break


if __name__ == "__main__":
    parser = ArgumentParser(
        description="Simulate a conversational task using a persona user and agent."
    )
    parser.add_argument(
        "--task_config", type=str, help="Task configuration file", required=True
    )
    parser.add_argument(
        "--persona_config", type=str, help="Persona configuration file", required=True
    )

    args = parser.parse_args()
    asyncio.run(run_simulation(args.task_config, args.persona_config))
