"""initial agents schema

Revision ID: 0001
Revises:
Create Date: 2026-07-08 19:46:39.881099

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from kavalai.db import VectorType, json_column, uuid_column

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _translated_schema_prefix() -> str:
    """Schema prefix for hand-written (raw SQL) DDL.

    ``schema_translate_map`` only rewrites compiled SQL, so raw statements
    must qualify the schema explicitly. The runner applies the map as
    ``{None: <schema>}`` on the connection — read it back from there.
    """
    bind = op.get_bind()
    translate_map = bind.get_execution_options().get("schema_translate_map") or {}
    schema = translate_map.get(None)
    return f'"{schema}".' if schema else ""


def upgrade() -> None:
    is_postgres = op.get_bind().dialect.name == "postgresql"
    if is_postgres:
        # rag_index stores pgvector embeddings; the type lives in ``public``
        # (see ``VectorType``), matching the previous plain-SQL migrations.
        op.execute("CREATE EXTENSION IF NOT EXISTS vector SCHEMA public")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agents",
        sa.Column("id", uuid_column(), nullable=False),
        sa.Column("name", sa.TEXT(), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("input_schema", json_column(), nullable=True),
        sa.Column("output_schema", json_column(), nullable=True),
        sa.Column("workflow", json_column(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "model_call_stats",
        sa.Column("id", uuid_column(), nullable=False),
        sa.Column("call_type", sa.TEXT(), nullable=False),
        sa.Column("model", sa.TEXT(), nullable=False),
        sa.Column("agent_id", uuid_column(), nullable=True),
        sa.Column("request_data", json_column(), nullable=True),
        sa.Column("response_data", json_column(), nullable=True),
        sa.Column("response_code", sa.Integer(), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("total_tokens", sa.Integer(), nullable=True),
        sa.Column("batch_size", sa.Integer(), nullable=True),
        sa.Column("duration_seconds", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("cost", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("currency", sa.TEXT(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("model_call_stats", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_model_call_stats_agent_id"), ["agent_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_model_call_stats_call_type"), ["call_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_model_call_stats_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_model_call_stats_model"), ["model"], unique=False
        )

    op.create_table(
        "rag_index",
        sa.Column("id", uuid_column(), nullable=False),
        sa.Column("model", sa.TEXT(), nullable=False),
        sa.Column("collection_name", sa.TEXT(), nullable=False),
        sa.Column("source_id", sa.TEXT(), nullable=False),
        sa.Column("content", sa.TEXT(), nullable=True),
        sa.Column("embedding_size", sa.Integer(), nullable=False),
        sa.Column("embedding", VectorType(), nullable=True),
        sa.Column("metadata", json_column(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("rag_index", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_rag_index_collection_name"),
            ["collection_name"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_rag_index_source_id"), ["source_id"], unique=False
        )

    if is_postgres:
        # Postgres-only performance indexes (GIN metadata filter + partial
        # HNSW similarity indexes per popular embedding size). Hand-written:
        # autogenerate cannot express these, and env.py's include_object
        # keeps them out of autogenerate/parity comparisons.
        prefix = _translated_schema_prefix()
        op.execute(
            f"CREATE INDEX idx_rag_index_metadata ON {prefix}rag_index "
            "USING gin (metadata)"
        )
        for dim in (768, 1024, 1536):
            op.execute(
                f"CREATE INDEX idx_rag_embedding_{dim} ON {prefix}rag_index "
                f"USING hnsw ((embedding::vector({dim})) vector_cosine_ops) "
                f"WHERE (embedding_size = {dim})"
            )

    op.create_table(
        "sessions",
        sa.Column("id", uuid_column(), nullable=False),
        sa.Column("agent_id", uuid_column(), nullable=False),
        sa.Column("external_id", sa.TEXT(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sessions_agent_id"), ["agent_id"], unique=False
        )

    op.create_table(
        "runs",
        sa.Column("id", uuid_column(), nullable=False),
        sa.Column("session_id", uuid_column(), nullable=False),
        sa.Column("input_data", json_column(), nullable=True),
        sa.Column("output_data", json_column(), nullable=True),
        sa.Column("context", json_column(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_runs_session_id"), ["session_id"], unique=False
        )

    op.create_table(
        "chat_messages",
        sa.Column("id", uuid_column(), nullable=False),
        sa.Column("agent_id", uuid_column(), nullable=False),
        sa.Column("session_id", uuid_column(), nullable=False),
        sa.Column("run_id", uuid_column(), nullable=True),
        sa.Column("role", sa.TEXT(), nullable=False),
        sa.Column("content", sa.TEXT(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("chat_messages", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_chat_messages_agent_id"), ["agent_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_chat_messages_run_id"), ["run_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_chat_messages_session_id"), ["session_id"], unique=False
        )

    op.create_table(
        "tasks",
        sa.Column("id", uuid_column(), nullable=False),
        sa.Column("agent_id", uuid_column(), nullable=True),
        sa.Column("session_id", uuid_column(), nullable=False),
        sa.Column("run_id", uuid_column(), nullable=False),
        sa.Column("inputs", json_column(), nullable=True),
        sa.Column("output", json_column(), nullable=True),
        sa.Column("name", sa.TEXT(), nullable=True),
        sa.Column("node_type", sa.TEXT(), nullable=True),
        sa.Column("prompt", sa.TEXT(), nullable=True),
        sa.Column("errors", json_column(), nullable=True),
        sa.Column("duration_seconds", sa.Numeric(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tasks_agent_id"), ["agent_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_tasks_run_id"), ["run_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_tasks_session_id"), ["session_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tasks_session_id"))
        batch_op.drop_index(batch_op.f("ix_tasks_run_id"))
        batch_op.drop_index(batch_op.f("ix_tasks_agent_id"))

    op.drop_table("tasks")
    with op.batch_alter_table("chat_messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_chat_messages_session_id"))
        batch_op.drop_index(batch_op.f("ix_chat_messages_run_id"))
        batch_op.drop_index(batch_op.f("ix_chat_messages_agent_id"))

    op.drop_table("chat_messages")
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_runs_session_id"))

    op.drop_table("runs")
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sessions_agent_id"))

    op.drop_table("sessions")
    with op.batch_alter_table("rag_index", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rag_index_source_id"))
        batch_op.drop_index(batch_op.f("ix_rag_index_collection_name"))

    op.drop_table("rag_index")
    with op.batch_alter_table("model_call_stats", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_model_call_stats_model"))
        batch_op.drop_index(batch_op.f("ix_model_call_stats_created_at"))
        batch_op.drop_index(batch_op.f("ix_model_call_stats_call_type"))
        batch_op.drop_index(batch_op.f("ix_model_call_stats_agent_id"))

    op.drop_table("model_call_stats")
    op.drop_table("agents")
    # ### end Alembic commands ###
